### ISSUE TITLE
"Scale Degrees" in ios is not working. 

### ISSUE THREAD

**Issue by sputnek** [ShacharHarshuv/open-ear#188] opened 2022-09-08 02:04 UTC
When "Scale Degrees" (in Open Ear) is selected, the label moves slightly to the right, but the exercise does not open for use. The remaining 6 exercises in the app are working.

**Comment by ShacharHarshuv** [comment] 2022-09-08 05:42
That's weird, I haven't got that complaint from any other user. Can you send a screenshot?
Also detail what device are you using

**Comment by sputnek** [comment] 2022-09-08 07:20
iPad Air
Model: MD789X/B (no longer produced)
IOS: 12.5.6 (a more recent IOS can not be updated)
Have deleted the OpenEar app and then reinstalled it - same problem.
Have also reinstalled the IOS - same problem.
"Scale Degrees" moves slightly to the right when I tap on it (i.e. it
recognises that I want to use that exercise, but it fails to open it). All
six of the other exercises both recognise I want to use their exercises and
they all open.
I have attached a screenshot, but I don't see how that will help.

**Comment by ShacharHarshuv** [comment] 2022-09-08 07:25
Hey, since this is an old model, can you please try on a newer device and let me know if the problem persist? If it's the case that it only reproduces in old models, it might not be worth investing time into it.

**Comment by ShacharHarshuv** [comment] 2022-09-08 20:16
Ahh I see. I'm sorry that it doesn't work for your device, I really don't know why and it's going to be very difficult for me to try to figure out.
I'm going to close this issue for now, let me know if there is some other way I can help. I will reopen if I other users encounter this issue.

**Closed by ShacharHarshuv** 2022-09-08 20:16 UTC
