### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [ShacharHarshuv/open-ear#116] opened 2022-04-29 16:07 UTC
```
> capacitor sync android
[error] Could not find the web assets directory: ./www.
        Please create it and make sure it has an index.html file. You can change the path of this directory in capacitor.config.json (webDir option). You may need to compile the web assets for your app (typically npm run build). More info: https://capacitorjs.com/docs/basics/workflow#sync-your-project
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor sync android exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
error Command failed with exit code 1.
```

How to create the www dir? Could you please take a look? Thanks!

**Comment by ShacharHarshuv** [comment] 2022-05-05 11:44
@proletarius101 can you help?

**Comment by licaon-kter** [comment] 2022-08-22 10:00
still an issue: https://gitlab.com/fdroid/fdroiddata/-/jobs/2913435241#L7109

**Comment by ShacharHarshuv** [comment] 2022-08-22 20:57
Hey, unfortunately I did not set up the F-Droid build and I know little about it. @proletarius101 is the one who set it up and I'm not sure how to fix this error. 
If you want, you can try to have a go at this yourself, everything should be committed in this repository. If you need something from me don't hesitate to let me know.

**Comment by JeanMax** [comment] 2024-10-02 14:24
Hello!

I looked a bit into this, it seems the old failing versions have been removed from the f-droid builds (as shown in @licaon-kter links). There's also a quite recent version in there (35798790 - "Update versions in android"). 

Everything builds ok, but... I feel like the last version isn't published for some reason (see https://f-droid.org/packages/com.openear.www). Maybe the `AutoUpdateMode: None` is causing this?

I'll investigate a bit more!

---

On a side note, it has been a long time since the last tag on that repository... is it a choice?

**Comment by licaon-kter** [comment] 2024-10-02 14:44
https://monitor.f-droid.org/builds/log/com.openear.www/46#site-footer is the latest fail which conveys more like _"server CPU does not support AVX512"_ maybe

> On a side note, it has been a long time since the last tag on that repository... is it a choice?

which tag? which repository?

latest is `1.9` per https://github.com/ShacharHarshuv/open-ear/tree/357987901c3dc437372488e546be771cb8e56e50

**Comment by ShacharHarshuv** [comment] 2024-10-02 14:51
> it has been a long time since the last tag on that repository... is it a choice?

Probably not. I never automated created tags and it's possible I've been kind of lazy. Do you need me to create a new tag with the up to date version?

**Comment by JeanMax** [comment] 2024-10-02 14:53
Not really, I was just curious if it was a way to indicate master isn't stable yet.

I'm really new to f-droid building process, so don't change anything yet for me :)

**Comment by licaon-kter** [comment] 2024-10-02 15:24
> Do you need me to create a new tag with the up to date version?

yes please, and for future ones :smile:

**Comment by JeanMax** [comment] 2024-10-02 15:27
> https://monitor.f-droid.org/builds/log/com.openear.www/46#site-footer is the latest fail which conveys more like _"server CPU does not support AVX512"_ maybe

It seems to work well on gitlab CI (https://gitlab.com/JeanMax/fdroiddata/-/jobs/7976167846), so I'm guessing the host is different... is there a way for me to try and reproduce this?

**Comment by licaon-kter** [comment] 2024-10-02 15:41
> is there a way for me to try and reproduce this?

just build on your 2012 era CPU :smile: 

or https://www.phoronix.com/news/Linux-5.19-Better-clearcpuid clear those about avx I guess, then try to build

**Comment by ShacharHarshuv** [comment] 2024-10-02 16:48
Just created a tag for the latest one if it helps: https://github.com/ShacharHarshuv/open-ear/releases/tag/1.9.0

**Comment by JeanMax** [comment] 2024-10-14 11:35
It's live! https://f-droid.org/en/packages/com.openear.www/
I did a quick test on my phone and it seems ok.

Basically the sharp dep is shipping its own binaries for libvips, so we installed them beforehand with apt to make sure they are compatible with the current builder cpu arch.

Don't hesitate to ping me if you have more issues with fdroid :)

**Comment by licaon-kter** [comment] 2024-10-14 11:37
@JeanMax thank you for the fix :+1:

**Closed** 2024-10-14 11:43 UTC
